#!/bin/bash

set -e

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <generated binding file>..." >&2
    exit 1
fi

staging_dir=$(mktemp -d "${TMPDIR:-/tmp}/paykit-bindings-postprocess.XXXXXX")
cleanup() {
    rm -rf "$staging_dir"
}
trap cleanup EXIT

original_files=("$@")
staged_files=()
kotlin_files=()

for input_index in "${!original_files[@]}"; do
    original_file="${original_files[$input_index]}"
    if [ ! -f "$original_file" ]; then
        echo "Error: generated binding input is not a file: $original_file" >&2
        exit 1
    fi

    case "$original_file" in
        *.kt)
            staged_file="$staging_dir/$input_index.kt"
            kotlin_files+=("$staged_file")
            ;;
        *) staged_file="$staging_dir/$input_index.binding" ;;
    esac

    cp "$original_file" "$staged_file"
    staged_files+=("$staged_file")
done

perl -0pi -e '
    s{// This file was autogenerated by some hot garbage in the `uniffi` crate\.}{// This file was autogenerated by UniFFI.}g;
    s{// Trust me, you don.t want to mess with it!}{// Do not edit this file directly.}g;
    s{[ \t]*// TODO: maybe we should log a warning if called more than once\?\n}{}g;
    s/PaykitFfi/Paykit/g;
    s/\b(FfiConverter(?:SequenceType|OptionType|Type)?)(Ffi)(?=[A-Z])/$1/g;
    s/\b(Ffi[A-Z][A-Za-z0-9_]*)\b/
        do {
            my $name = $1;
            ($name =~ m{^Ffi(?:Converter|Type)}) ? $name : substr($name, 3)
        }
    /gex;
' "${staged_files[@]}"

if [ "${#kotlin_files[@]}" -gt 0 ]; then
    perl -0pi -e '
        BEGIN {
            @types = qw(
                AllowanceAmountRange
                AllowancePeriod
                AllowancePeriodLimit
                AllowanceTerms
            );
        }

        for $type (@types) {
            $declaration = "public open class $type: Disposable, ${type}Interface {";
            $override = "    override fun toString(): String = \"$type(<redacted>)\"";

            $local_class_count = () = /^\Q$declaration\E$/mg;
            $class_count{$type} += $local_class_count;
            $local_override_count = () = /^\Q$override\E$/mg;

            if ($local_class_count == 1 && $local_override_count == 0) {
                $injection_count = s/^\Q$declaration\E\n/$declaration\n$override\n/mg;
                die "failed to inject Kotlin redacted toString for $type\n"
                    unless $injection_count == 1;
            }

            $override_count{$type} += () = /^\Q$override\E$/mg;
            $adjacent_count{$type} += () = /^\Q$declaration\E\n\Q$override\E$/mg;
        }

        END {
            for $type (@types) {
                die "expected exactly one generated Kotlin $type class, found $class_count{$type}\n"
                    unless $class_count{$type} == 1;
                die "expected exactly one Kotlin $type redacted toString, found $override_count{$type}\n"
                    unless $override_count{$type} == 1;
                die "Kotlin $type redacted toString is not inside its wrapper class\n"
                    unless $adjacent_count{$type} == 1;
            }
        }
    ' "${kotlin_files[@]}"
fi

for input_index in "${!original_files[@]}"; do
    cp "${staged_files[$input_index]}" "${original_files[$input_index]}"
done
