#!/bin/bash

set -e

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <generated binding file>..." >&2
    exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PAYKIT_REDACTED_TYPES=$(tr '\n' ' ' < "$SCRIPT_DIR/redacted_binding_records.txt")
export PAYKIT_REDACTED_TYPES

perl -0pi -e '
    s{// This file was autogenerated by some hot garbage in the `uniffi` crate\.}{// This file was autogenerated by UniFFI.}g;
    s{// Trust me, you don.t want to mess with it!}{// Do not edit this file directly.}g;
    s{[ \t]*// TODO: maybe we should log a warning if called more than once\?\n}{}g;
    s/PaykitFfi/Paykit/g;
    s/\b(FfiConverter(?:SequenceType|OptionType|Type)?)(Ffi)(?=[A-Z])/$1/g;
    s/\b(Ffi[A-Z][A-Za-z0-9_]*)\b/
        do {
            my $name = $1;
            ($name =~ m{^Ffi(?:Converter|Type)}) ? $name : substr($name, 3)
        }
    /gex;
' "$@"

perl -0pi -e '
    for my $type (grep { length } split /\s+/, $ENV{PAYKIT_REDACTED_TYPES}) {
        my $override = "    override fun toString(): kotlin.String = \"${type}(<redacted>)\"\n\n";
        s/\Q$override\E//g;
        s/(public data class \Q$type\E \(.*?\n\)[^{\n]*\{\n)(.*?)(    public companion object)/$1$2$override$3/gs;
    }
' "$@"
