// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(paykitFFI)
import paykitFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_paykit_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_paykit_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePaykitInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct FfiHandshakeProgress {
    public var status: String
    public var handleId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(status: String, handleId: String) {
        self.status = status
        self.handleId = handleId
    }
}

#if compiler(>=6)
extension FfiHandshakeProgress: Sendable {}
#endif


extension FfiHandshakeProgress: Equatable, Hashable {
    public static func ==(lhs: FfiHandshakeProgress, rhs: FfiHandshakeProgress) -> Bool {
        if lhs.status != rhs.status {
            return false
        }
        if lhs.handleId != rhs.handleId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(status)
        hasher.combine(handleId)
    }
}

extension FfiHandshakeProgress: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHandshakeProgress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHandshakeProgress {
        return
            try FfiHandshakeProgress(
                status: FfiConverterString.read(from: &buf),
                handleId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiHandshakeProgress, into buf: inout [UInt8]) {
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.handleId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHandshakeProgress_lift(_ buf: RustBuffer) throws -> FfiHandshakeProgress {
    return try FfiConverterTypeFfiHandshakeProgress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHandshakeProgress_lower(_ value: FfiHandshakeProgress) -> RustBuffer {
    return FfiConverterTypeFfiHandshakeProgress.lower(value)
}


public struct FfiIssuedReceipt {
    public var reference: String
    public var location: String
    /**
     * Sensitive raw receipt decryption key material. Do not log.
     */
    public var key: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reference: String, location: String,
        /**
         * Sensitive raw receipt decryption key material. Do not log.
         */key: String) {
        self.reference = reference
        self.location = location
        self.key = key
    }
}

#if compiler(>=6)
extension FfiIssuedReceipt: Sendable {}
#endif


extension FfiIssuedReceipt: Equatable, Hashable {
    public static func ==(lhs: FfiIssuedReceipt, rhs: FfiIssuedReceipt) -> Bool {
        if lhs.reference != rhs.reference {
            return false
        }
        if lhs.location != rhs.location {
            return false
        }
        if lhs.key != rhs.key {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(reference)
        hasher.combine(location)
        hasher.combine(key)
    }
}

extension FfiIssuedReceipt: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiIssuedReceipt: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiIssuedReceipt {
        return
            try FfiIssuedReceipt(
                reference: FfiConverterString.read(from: &buf),
                location: FfiConverterString.read(from: &buf),
                key: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiIssuedReceipt, into buf: inout [UInt8]) {
        FfiConverterString.write(value.reference, into: &buf)
        FfiConverterString.write(value.location, into: &buf)
        FfiConverterString.write(value.key, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIssuedReceipt_lift(_ buf: RustBuffer) throws -> FfiIssuedReceipt {
    return try FfiConverterTypeFfiIssuedReceipt.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIssuedReceipt_lower(_ value: FfiIssuedReceipt) -> RustBuffer {
    return FfiConverterTypeFfiIssuedReceipt.lower(value)
}


public struct FfiPaymentEntry {
    public var methodId: String
    public var endpointData: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(methodId: String, endpointData: String) {
        self.methodId = methodId
        self.endpointData = endpointData
    }
}

#if compiler(>=6)
extension FfiPaymentEntry: Sendable {}
#endif


extension FfiPaymentEntry: Equatable, Hashable {
    public static func ==(lhs: FfiPaymentEntry, rhs: FfiPaymentEntry) -> Bool {
        if lhs.methodId != rhs.methodId {
            return false
        }
        if lhs.endpointData != rhs.endpointData {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(methodId)
        hasher.combine(endpointData)
    }
}

extension FfiPaymentEntry: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPaymentEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPaymentEntry {
        return
            try FfiPaymentEntry(
                methodId: FfiConverterString.read(from: &buf),
                endpointData: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPaymentEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.methodId, into: &buf)
        FfiConverterString.write(value.endpointData, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPaymentEntry_lift(_ buf: RustBuffer) throws -> FfiPaymentEntry {
    return try FfiConverterTypeFfiPaymentEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPaymentEntry_lower(_ value: FfiPaymentEntry) -> RustBuffer {
    return FfiConverterTypeFfiPaymentEntry.lower(value)
}


public struct FfiPrivatePaymentsPayload {
    public var reference: String
    public var entries: [FfiPaymentEntry]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reference: String, entries: [FfiPaymentEntry]) {
        self.reference = reference
        self.entries = entries
    }
}

#if compiler(>=6)
extension FfiPrivatePaymentsPayload: Sendable {}
#endif


extension FfiPrivatePaymentsPayload: Equatable, Hashable {
    public static func ==(lhs: FfiPrivatePaymentsPayload, rhs: FfiPrivatePaymentsPayload) -> Bool {
        if lhs.reference != rhs.reference {
            return false
        }
        if lhs.entries != rhs.entries {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(reference)
        hasher.combine(entries)
    }
}

extension FfiPrivatePaymentsPayload: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPrivatePaymentsPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPrivatePaymentsPayload {
        return
            try FfiPrivatePaymentsPayload(
                reference: FfiConverterString.read(from: &buf),
                entries: FfiConverterSequenceTypeFfiPaymentEntry.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPrivatePaymentsPayload, into buf: inout [UInt8]) {
        FfiConverterString.write(value.reference, into: &buf)
        FfiConverterSequenceTypeFfiPaymentEntry.write(value.entries, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPrivatePaymentsPayload_lift(_ buf: RustBuffer) throws -> FfiPrivatePaymentsPayload {
    return try FfiConverterTypeFfiPrivatePaymentsPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPrivatePaymentsPayload_lower(_ value: FfiPrivatePaymentsPayload) -> RustBuffer {
    return FfiConverterTypeFfiPrivatePaymentsPayload.lower(value)
}


public struct FfiReceipt {
    public var reference: String
    public var recipientPublicKey: String
    public var paymentMethod: String?
    public var amount: String?
    public var currency: String?
    public var metadata: [FfiReceiptMetadataEntry]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reference: String, recipientPublicKey: String, paymentMethod: String?, amount: String?, currency: String?, metadata: [FfiReceiptMetadataEntry]) {
        self.reference = reference
        self.recipientPublicKey = recipientPublicKey
        self.paymentMethod = paymentMethod
        self.amount = amount
        self.currency = currency
        self.metadata = metadata
    }
}

#if compiler(>=6)
extension FfiReceipt: Sendable {}
#endif


extension FfiReceipt: Equatable, Hashable {
    public static func ==(lhs: FfiReceipt, rhs: FfiReceipt) -> Bool {
        if lhs.reference != rhs.reference {
            return false
        }
        if lhs.recipientPublicKey != rhs.recipientPublicKey {
            return false
        }
        if lhs.paymentMethod != rhs.paymentMethod {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.currency != rhs.currency {
            return false
        }
        if lhs.metadata != rhs.metadata {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(reference)
        hasher.combine(recipientPublicKey)
        hasher.combine(paymentMethod)
        hasher.combine(amount)
        hasher.combine(currency)
        hasher.combine(metadata)
    }
}

extension FfiReceipt: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiReceipt: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiReceipt {
        return
            try FfiReceipt(
                reference: FfiConverterString.read(from: &buf),
                recipientPublicKey: FfiConverterString.read(from: &buf),
                paymentMethod: FfiConverterOptionString.read(from: &buf),
                amount: FfiConverterOptionString.read(from: &buf),
                currency: FfiConverterOptionString.read(from: &buf),
                metadata: FfiConverterSequenceTypeFfiReceiptMetadataEntry.read(from: &buf)
        )
    }

    public static func write(_ value: FfiReceipt, into buf: inout [UInt8]) {
        FfiConverterString.write(value.reference, into: &buf)
        FfiConverterString.write(value.recipientPublicKey, into: &buf)
        FfiConverterOptionString.write(value.paymentMethod, into: &buf)
        FfiConverterOptionString.write(value.amount, into: &buf)
        FfiConverterOptionString.write(value.currency, into: &buf)
        FfiConverterSequenceTypeFfiReceiptMetadataEntry.write(value.metadata, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceipt_lift(_ buf: RustBuffer) throws -> FfiReceipt {
    return try FfiConverterTypeFfiReceipt.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceipt_lower(_ value: FfiReceipt) -> RustBuffer {
    return FfiConverterTypeFfiReceipt.lower(value)
}


public struct FfiReceiptAccess {
    public var version: UInt32
    public var reference: String
    public var location: String
    /**
     * Sensitive raw receipt decryption key material. Do not log.
     */
    public var key: String
    public var algorithm: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(version: UInt32, reference: String, location: String,
        /**
         * Sensitive raw receipt decryption key material. Do not log.
         */key: String, algorithm: String) {
        self.version = version
        self.reference = reference
        self.location = location
        self.key = key
        self.algorithm = algorithm
    }
}

#if compiler(>=6)
extension FfiReceiptAccess: Sendable {}
#endif


extension FfiReceiptAccess: Equatable, Hashable {
    public static func ==(lhs: FfiReceiptAccess, rhs: FfiReceiptAccess) -> Bool {
        if lhs.version != rhs.version {
            return false
        }
        if lhs.reference != rhs.reference {
            return false
        }
        if lhs.location != rhs.location {
            return false
        }
        if lhs.key != rhs.key {
            return false
        }
        if lhs.algorithm != rhs.algorithm {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(version)
        hasher.combine(reference)
        hasher.combine(location)
        hasher.combine(key)
        hasher.combine(algorithm)
    }
}

extension FfiReceiptAccess: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiReceiptAccess: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiReceiptAccess {
        return
            try FfiReceiptAccess(
                version: FfiConverterUInt32.read(from: &buf),
                reference: FfiConverterString.read(from: &buf),
                location: FfiConverterString.read(from: &buf),
                key: FfiConverterString.read(from: &buf),
                algorithm: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiReceiptAccess, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.version, into: &buf)
        FfiConverterString.write(value.reference, into: &buf)
        FfiConverterString.write(value.location, into: &buf)
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.algorithm, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceiptAccess_lift(_ buf: RustBuffer) throws -> FfiReceiptAccess {
    return try FfiConverterTypeFfiReceiptAccess.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceiptAccess_lower(_ value: FfiReceiptAccess) -> RustBuffer {
    return FfiConverterTypeFfiReceiptAccess.lower(value)
}


public struct FfiReceiptDraft {
    public var reference: String
    public var paymentMethod: String?
    public var amount: String?
    public var currency: String?
    public var metadata: [FfiReceiptMetadataEntry]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reference: String, paymentMethod: String?, amount: String?, currency: String?, metadata: [FfiReceiptMetadataEntry]) {
        self.reference = reference
        self.paymentMethod = paymentMethod
        self.amount = amount
        self.currency = currency
        self.metadata = metadata
    }
}

#if compiler(>=6)
extension FfiReceiptDraft: Sendable {}
#endif


extension FfiReceiptDraft: Equatable, Hashable {
    public static func ==(lhs: FfiReceiptDraft, rhs: FfiReceiptDraft) -> Bool {
        if lhs.reference != rhs.reference {
            return false
        }
        if lhs.paymentMethod != rhs.paymentMethod {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.currency != rhs.currency {
            return false
        }
        if lhs.metadata != rhs.metadata {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(reference)
        hasher.combine(paymentMethod)
        hasher.combine(amount)
        hasher.combine(currency)
        hasher.combine(metadata)
    }
}

extension FfiReceiptDraft: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiReceiptDraft: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiReceiptDraft {
        return
            try FfiReceiptDraft(
                reference: FfiConverterString.read(from: &buf),
                paymentMethod: FfiConverterOptionString.read(from: &buf),
                amount: FfiConverterOptionString.read(from: &buf),
                currency: FfiConverterOptionString.read(from: &buf),
                metadata: FfiConverterSequenceTypeFfiReceiptMetadataEntry.read(from: &buf)
        )
    }

    public static func write(_ value: FfiReceiptDraft, into buf: inout [UInt8]) {
        FfiConverterString.write(value.reference, into: &buf)
        FfiConverterOptionString.write(value.paymentMethod, into: &buf)
        FfiConverterOptionString.write(value.amount, into: &buf)
        FfiConverterOptionString.write(value.currency, into: &buf)
        FfiConverterSequenceTypeFfiReceiptMetadataEntry.write(value.metadata, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceiptDraft_lift(_ buf: RustBuffer) throws -> FfiReceiptDraft {
    return try FfiConverterTypeFfiReceiptDraft.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceiptDraft_lower(_ value: FfiReceiptDraft) -> RustBuffer {
    return FfiConverterTypeFfiReceiptDraft.lower(value)
}


public struct FfiReceiptMetadataEntry {
    public var key: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, value: String) {
        self.key = key
        self.value = value
    }
}

#if compiler(>=6)
extension FfiReceiptMetadataEntry: Sendable {}
#endif


extension FfiReceiptMetadataEntry: Equatable, Hashable {
    public static func ==(lhs: FfiReceiptMetadataEntry, rhs: FfiReceiptMetadataEntry) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(value)
    }
}

extension FfiReceiptMetadataEntry: Codable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiReceiptMetadataEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiReceiptMetadataEntry {
        return
            try FfiReceiptMetadataEntry(
                key: FfiConverterString.read(from: &buf),
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiReceiptMetadataEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceiptMetadataEntry_lift(_ buf: RustBuffer) throws -> FfiReceiptMetadataEntry {
    return try FfiConverterTypeFfiReceiptMetadataEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReceiptMetadataEntry_lower(_ value: FfiReceiptMetadataEntry) -> RustBuffer {
    return FfiConverterTypeFfiReceiptMetadataEntry.lower(value)
}


public enum PaykitFfiError: Swift.Error {



    case Transport(reason: String
    )
    case NotFound(reason: String
    )
    case InvalidData(reason: String
    )
    case Validation(reason: String
    )
    case Session(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePaykitFfiError: FfiConverterRustBuffer {
    typealias SwiftType = PaykitFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PaykitFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Transport(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotFound(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidData(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Validation(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Session(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PaykitFfiError, into buf: inout [UInt8]) {
        switch value {





        case let .Transport(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)


        case let .NotFound(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)


        case let .InvalidData(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)


        case let .Validation(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)


        case let .Session(reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(reason, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaykitFfiError_lift(_ buf: RustBuffer) throws -> PaykitFfiError {
    return try FfiConverterTypePaykitFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaykitFfiError_lower(_ value: PaykitFfiError) -> RustBuffer {
    return FfiConverterTypePaykitFfiError.lower(value)
}


extension PaykitFfiError: Equatable, Hashable {}

extension PaykitFfiError: Codable {}




extension PaykitFfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiPrivatePaymentsPayload: FfiConverterRustBuffer {
    typealias SwiftType = FfiPrivatePaymentsPayload?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiPrivatePaymentsPayload.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiPrivatePaymentsPayload.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiPaymentEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPaymentEntry]

    public static func write(_ value: [FfiPaymentEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPaymentEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPaymentEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPaymentEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiPaymentEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiReceiptAccess: FfiConverterRustBuffer {
    typealias SwiftType = [FfiReceiptAccess]

    public static func write(_ value: [FfiReceiptAccess], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiReceiptAccess.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiReceiptAccess] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiReceiptAccess]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiReceiptAccess.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiReceiptMetadataEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FfiReceiptMetadataEntry]

    public static func write(_ value: [FfiReceiptMetadataEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiReceiptMetadataEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiReceiptMetadataEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiReceiptMetadataEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiReceiptMetadataEntry.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePaykitInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Start a private-payment encrypted link as the responder.
 */
public func paykitAcceptEncryptedLink(secretKeyHex: String, senderPublicKey: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_accept_encrypted_link(FfiConverterString.lower(secretKeyHex),FfiConverterString.lower(senderPublicKey)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Advance an encrypted-link handshake by one polling-safe step.
 *
 * Returns status `"pending"` with the same handshake handle, or `"complete"`
 * with a new encrypted-link handle.
 */
public func paykitAdvanceHandshake(handshakeId: String)async throws  -> FfiHandshakeProgress  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_advance_handshake(FfiConverterString.lower(handshakeId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiHandshakeProgress_lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Close an established encrypted link and remove its FFI handle.
 */
public func paykitCloseEncryptedLink(linkId: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_close_encrypted_link(FfiConverterString.lower(linkId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Decrypt an encrypted receipt payload fetched from the homeserver.
 *
 * `key` and `location` should come from a `FfiReceiptAccess` message. The key is
 * sensitive; do not log it. Decryption authenticates `location` as associated
 * data and rejects plaintext whose reference does not match that location.
 */
public func paykitDecryptReceipt(encryptedJson: String, key: String, location: String)throws  -> FfiReceipt  {
    return try  FfiConverterTypeFfiReceipt_lift(try rustCallWithError(FfiConverterTypePaykitFfiError_lift) {
    uniffi_paykit_fn_func_paykit_decrypt_receipt(
        FfiConverterString.lower(encryptedJson),
        FfiConverterString.lower(key),
        FfiConverterString.lower(location),$0
    )
})
}
/**
 * Default maximum number of consecutive handshake recovery attempts.
 */
public func paykitDefaultMaxRecoveryAttempts() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_paykit_fn_func_paykit_default_max_recovery_attempts($0
    )
})
}
/**
 * Default maximum number of automatic private-payment send retries.
 */
public func paykitDefaultMaxSendRetries() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_paykit_fn_func_paykit_default_max_send_retries($0
    )
})
}
/**
 * Drop an in-progress encrypted-link handshake handle.
 */
public func paykitDropEncryptedLinkHandshake(handshakeId: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_drop_encrypted_link_handshake(FfiConverterString.lower(handshakeId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Return the remote peer embedded in a handshake snapshot.
 */
public func paykitEncryptedLinkHandshakeSnapshotRecipient(snapshotHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePaykitFfiError_lift) {
    uniffi_paykit_fn_func_paykit_encrypted_link_handshake_snapshot_recipient(
        FfiConverterString.lower(snapshotHex),$0
    )
})
}
/**
 * Return the remote peer embedded in an encrypted-link snapshot.
 */
public func paykitEncryptedLinkSnapshotRecipient(snapshotHex: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePaykitFfiError_lift) {
    uniffi_paykit_fn_func_paykit_encrypted_link_snapshot_recipient(
        FfiConverterString.lower(snapshotHex),$0
    )
})
}
/**
 * Exports the current session secret for persistence across app restarts.
 *
 * Returns the compact `<pubkey_z32>:<cookie_secret>` string that can be
 * passed back to `paykit_import_session` on next cold start.
 */
public func paykitExportSession()async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_export_session(
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Discard the local session without contacting the homeserver.
 *
 * Idempotent — safe to call even when no session exists.
 * The server-side session will expire on its own.
 */
public func paykitForceSignOut()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_force_sign_out(
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil

        )
}
/**
 * Generate a fresh UUID-v4 payment reference for private payment correlation.
 */
public func paykitGeneratePaymentReference() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_paykit_fn_func_paykit_generate_payment_reference($0
    )
})
}
/**
 * Returns the public key of the currently authenticated user, or `None`.
 */
public func paykitGetCurrentPublicKey()async  -> String?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_get_current_public_key(
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionString.lift,
            errorHandler: nil

        )
}
/**
 * Fetch a single payment endpoint for a user and method. Returns `None` if not set.
 */
public func paykitGetPaymentEndpoint(publicKey: String, methodId: String)async throws  -> String?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_get_payment_endpoint(FfiConverterString.lower(publicKey),FfiConverterString.lower(methodId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Fetch all published payment methods for a user.
 */
public func paykitGetPaymentList(publicKey: String)async throws  -> [FfiPaymentEntry]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_get_payment_list(FfiConverterString.lower(publicKey)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiPaymentEntry.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Receive and decrypt the latest private payments envelope from an established link.
 */
public func paykitGetPrivatePayments(linkId: String)async throws  -> FfiPrivatePaymentsPayload?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_get_private_payments(FfiConverterString.lower(linkId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeFfiPrivatePaymentsPayload.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Receive all currently available receipt access descriptors in FIFO order.
 *
 * Returns an empty vector when no receipt access messages are available. Each
 * returned `key` is sensitive decryption material. Do not log it.
 */
public func paykitGetReceiptAccess(linkId: String)async throws  -> [FfiReceiptAccess]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_get_receipt_access(FfiConverterString.lower(linkId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiReceiptAccess.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Import a session from a Pubky Ring auth flow.
 *
 * Accepts a compact session secret (`<pubkey_z32>:<cookie_secret>`) produced
 * by `PubkySession::export_secret()`. Validates with the homeserver and stores
 * the session for subsequent write operations.
 */
public func paykitImportSession(sessionSecret: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_import_session(FfiConverterString.lower(sessionSecret)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Create the Pubky SDK facade and initialize logging. Call once at app startup.
 *
 * Targets the **production** network.
 *
 * Safe to call multiple times — subsequent calls are no-ops if the first
 * succeeded. If it fails (e.g. network issue), call it again to retry.
 */
public func paykitInitialize()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_initialize(
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Start a private-payment encrypted link as the initiator.
 */
public func paykitInitiateEncryptedLink(secretKeyHex: String, receiverPublicKey: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_initiate_encrypted_link(FfiConverterString.lower(secretKeyHex),FfiConverterString.lower(receiverPublicKey)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Returns `true` if an authenticated session is currently active.
 */
public func paykitIsAuthenticated()async  -> Bool  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_is_authenticated(
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_i8,
            completeFunc: ffi_paykit_rust_future_complete_i8,
            freeFunc: ffi_paykit_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil

        )
}
/**
 * Store an encrypted receipt and send receipt access over an established link.
 *
 * The returned `key` is sensitive decryption material. Do not log it or store it
 * outside platform secure storage.
 */
public func paykitIssueReceipt(linkId: String, draft: FfiReceiptDraft)async throws  -> FfiIssuedReceipt  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_issue_receipt(FfiConverterString.lower(linkId),FfiConverterTypeFfiReceiptDraft_lower(draft)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiIssuedReceipt_lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Return the canonical homeserver receipt location for a payment reference.
 */
public func paykitReceiptLocation(reference: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePaykitFfiError_lift) {
    uniffi_paykit_fn_func_paykit_receipt_location(
        FfiConverterString.lower(reference),$0
    )
})
}
/**
 * Remove a payment endpoint for the authenticated user.
 */
public func paykitRemovePaymentEndpoint(methodId: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_remove_payment_endpoint(FfiConverterString.lower(methodId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Restore an established encrypted link from a serialized snapshot.
 */
public func paykitRestoreEncryptedLink(secretKeyHex: String, snapshotHex: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_restore_encrypted_link(FfiConverterString.lower(secretKeyHex),FfiConverterString.lower(snapshotHex)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Restore an in-progress encrypted-link handshake from a serialized snapshot.
 */
public func paykitRestoreEncryptedLinkHandshake(secretKeyHex: String, snapshotHex: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_restore_encrypted_link_handshake(FfiConverterString.lower(secretKeyHex),FfiConverterString.lower(snapshotHex)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Serialize an established encrypted link snapshot for durable storage.
 */
public func paykitSerializeEncryptedLink(linkId: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_serialize_encrypted_link(FfiConverterString.lower(linkId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Serialize an in-progress handshake snapshot for durable storage.
 */
public func paykitSerializeEncryptedLinkHandshake(handshakeId: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_serialize_encrypted_link_handshake(FfiConverterString.lower(handshakeId)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Configure automatic recovery attempts for a pending encrypted-link handshake.
 */
public func paykitSetEncryptedLinkHandshakeMaxRecoveryAttempts(handshakeId: String, max: UInt32)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_set_encrypted_link_handshake_max_recovery_attempts(FfiConverterString.lower(handshakeId),FfiConverterUInt32.lower(max)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Configure automatic send retries for an established encrypted link.
 */
public func paykitSetEncryptedLinkMaxSendRetries(linkId: String, max: UInt32)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_set_encrypted_link_max_send_retries(FfiConverterString.lower(linkId),FfiConverterUInt32.lower(max)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Publish or update a payment endpoint for the authenticated user.
 */
public func paykitSetPaymentEndpoint(methodId: String, endpointData: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_set_payment_endpoint(FfiConverterString.lower(methodId),FfiConverterString.lower(endpointData)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Encrypt and send the complete private payments envelope over an established link.
 */
public func paykitSetPrivatePayments(linkId: String, payload: FfiPrivatePaymentsPayload)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_set_private_payments(FfiConverterString.lower(linkId),FfiConverterTypeFfiPrivatePaymentsPayload_lower(payload)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Sign in with a raw secret key. Only available with the `dev-auth`
 * feature (enabled by default, disable for production builds).
 *
 * The homeserver is resolved automatically via PKDNS.
 */
public func paykitSignIn(secretKeyHex: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_sign_in(FfiConverterString.lower(secretKeyHex)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * End the current session on the homeserver and clear local state.
 *
 * If the server request fails the session is restored so no data is lost.
 */
public func paykitSignOut()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_sign_out(
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_void,
            completeFunc: ffi_paykit_rust_future_complete_void,
            freeFunc: ffi_paykit_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}
/**
 * Sign up for a new account using a raw secret key. Only available with
 * the `dev-auth` feature (enabled by default, disable for production builds).
 */
public func paykitSignUp(secretKeyHex: String, homeserverPublicKey: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_paykit_fn_func_paykit_sign_up(FfiConverterString.lower(secretKeyHex),FfiConverterString.lower(homeserverPublicKey)
                )
            },
            pollFunc: ffi_paykit_rust_future_poll_rust_buffer,
            completeFunc: ffi_paykit_rust_future_complete_rust_buffer,
            freeFunc: ffi_paykit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypePaykitFfiError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_paykit_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_accept_encrypted_link() != 21287) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_advance_handshake() != 29494) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_close_encrypted_link() != 14508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_decrypt_receipt() != 38169) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_default_max_recovery_attempts() != 23339) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_default_max_send_retries() != 12386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_drop_encrypted_link_handshake() != 43355) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_encrypted_link_handshake_snapshot_recipient() != 33656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_encrypted_link_snapshot_recipient() != 21528) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_export_session() != 8374) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_force_sign_out() != 30515) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_generate_payment_reference() != 10899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_get_current_public_key() != 28037) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_get_payment_endpoint() != 52733) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_get_payment_list() != 63326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_get_private_payments() != 50390) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_get_receipt_access() != 29689) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_import_session() != 29532) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_initialize() != 62040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_initiate_encrypted_link() != 52625) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_is_authenticated() != 34745) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_issue_receipt() != 32321) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_receipt_location() != 36124) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_remove_payment_endpoint() != 52853) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_restore_encrypted_link() != 31079) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_restore_encrypted_link_handshake() != 23271) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_serialize_encrypted_link() != 33771) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_serialize_encrypted_link_handshake() != 27705) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_set_encrypted_link_handshake_max_recovery_attempts() != 38386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_set_encrypted_link_max_send_retries() != 4305) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_set_payment_endpoint() != 62857) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_set_private_payments() != 52873) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_sign_in() != 50011) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_sign_out() != 116) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_paykit_checksum_func_paykit_sign_up() != 45538) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePaykitInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all